/**
 * OimoPhysics REV 1.0.0
 * @author Saharan / http://el-ement.com/
 * 
 * Oimo.js 2014
 * @author LoTh / http://3dflashlo.wordpress.com/
 */
 
var OIMO = { REVISION: 'REV.1.0.0' };

OIMO.SHAPE_NULL = 0x0;
OIMO.SHAPE_SPHERE = 0x1;
OIMO.SHAPE_BOX = 0x2;
OIMO.SHAPE_CYLINDER = 0x3;

OIMO.MAX_BODIES = 16384;
OIMO.WORLD_MAX_SHAPES = 32768;
OIMO.MAX_CONTACTS = 65536;
OIMO.MAX_JOINTS = 16384;
OIMO.MAX_CONSTRAINTS = OIMO.MAX_CONTACTS + OIMO.MAX_JOINTS;
OIMO.MAX_SHAPES = 64;

OIMO.BODY_DYNAMIC = 0x0;
OIMO.BODY_STATIC = 0x1;

OIMO.WORLD_SCALE = 100;
OIMO.INV_SCALE = 0.01;

OIMO.TO_RAD = Math.PI / 180;

OIMO.nextID = 0;