OIMO.DistanceJoint = function(config,rigid1,rigid2,distance){
    OIMO.Joint.call( this );

    this.posError=NaN;
    this.norX=NaN;
    this.norY=NaN;
    this.norZ=NaN;
    this.relPos1X=NaN;
    this.relPos1Y=NaN;
    this.relPos1Z=NaN;
    this.relPos2X=NaN;
    this.relPos2Y=NaN;
    this.relPos2Z=NaN;
    this.norTorque1X=NaN;
    this.norTorque1Y=NaN;
    this.norTorque1Z=NaN;
    this.norTorque2X=NaN;
    this.norTorque2Y=NaN;
    this.norTorque2Z=NaN;
    this.norTorqueUnit1X=NaN;
    this.norTorqueUnit1Y=NaN;
    this.norTorqueUnit1Z=NaN;
    this.norTorqueUnit2X=NaN;
    this.norTorqueUnit2Y=NaN;
    this.norTorqueUnit2Z=NaN;
    this.invI1e00=NaN;
    this.invI1e01=NaN;
    this.invI1e02=NaN;
    this.invI1e10=NaN;
    this.invI1e11=NaN;
    this.invI1e12=NaN;
    this.invI1e20=NaN;
    this.invI1e21=NaN;
    this.invI1e22=NaN;
    this.invI2e00=NaN;
    this.invI2e01=NaN;
    this.invI2e02=NaN;
    this.invI2e10=NaN;
    this.invI2e11=NaN;
    this.invI2e12=NaN;
    this.invI2e20=NaN;
    this.invI2e21=NaN;
    this.invI2e22=NaN;
    this.normalDenominator=NaN;
    this.targetNormalVelocity=NaN;

    this.body1=rigid1;
    this.body2=rigid2;
    this.connection1.connected=rigid2;
    this.connection2.connected=rigid1;
    this.distance=distance;
    this.allowCollision=config.allowCollision;
    this.localRelativeAnchorPosition1.copy(config.localRelativeAnchorPosition1);
    this.localRelativeAnchorPosition2.copy(config.localRelativeAnchorPosition2);
    this.type=this.JOINT_DISTANCE;
    this.lVel1=this.body1.linearVelocity;
    this.lVel2=this.body2.linearVelocity;
    this.aVel1=this.body1.angularVelocity;
    this.aVel2=this.body2.angularVelocity;
    this.invM1=this.body1.invertMass;
    this.invM2=this.body2.invertMass;
    this.impulse=0;
}
OIMO.DistanceJoint.prototype = Object.create( OIMO.Joint.prototype );
OIMO.DistanceJoint.prototype.preSolve = function (timeStep,invTimeStep) {
    var tmpM;
    var tmp1X;
    var tmp1Y;
    var tmp1Z;
    var tmp2X;
    var tmp2Y;
    var tmp2Z;
    tmpM=this.body1.rotation.elements;
    tmp1X=this.localRelativeAnchorPosition1.x;
    tmp1Y=this.localRelativeAnchorPosition1.y;
    tmp1Z=this.localRelativeAnchorPosition1.z;
    this.relPos1X=this.relativeAnchorPosition1.x=tmp1X*tmpM[0]+tmp1Y*tmpM[1]+tmp1Z*tmpM[2];
    this.relPos1Y=this.relativeAnchorPosition1.y=tmp1X*tmpM[3]+tmp1Y*tmpM[4]+tmp1Z*tmpM[5];
    this.relPos1Z=this.relativeAnchorPosition1.z=tmp1X*tmpM[6]+tmp1Y*tmpM[7]+tmp1Z*tmpM[8];
    tmpM=this.body2.rotation.elements;
    tmp1X=this.localRelativeAnchorPosition2.x;
    tmp1Y=this.localRelativeAnchorPosition2.y;
    tmp1Z=this.localRelativeAnchorPosition2.z;
    this.relPos2X=this.relativeAnchorPosition2.x=tmp1X*tmpM[0]+tmp1Y*tmpM[1]+tmp1Z*tmpM[2];
    this.relPos2Y=this.relativeAnchorPosition2.y=tmp1X*tmpM[3]+tmp1Y*tmpM[4]+tmp1Z*tmpM[5];
    this.relPos2Z=this.relativeAnchorPosition2.z=tmp1X*tmpM[6]+tmp1Y*tmpM[7]+tmp1Z*tmpM[8];
    this.norX=(this.anchorPosition2.x=this.relPos2X+this.body2.position.x)-(this.anchorPosition1.x=this.relPos1X+this.body1.position.x);
    this.norY=(this.anchorPosition2.y=this.relPos2Y+this.body2.position.y)-(this.anchorPosition1.y=this.relPos1Y+this.body1.position.y);
    this.norZ=(this.anchorPosition2.z=this.relPos2Z+this.body2.position.z)-(this.anchorPosition1.z=this.relPos1Z+this.body1.position.z);
    tmp1X=Math.sqrt(this.norX*this.norX+this.norY*this.norY+this.norZ*this.norZ);
    this.posError=this.distance-tmp1X;
    if(tmp1X>0)tmp1X=1/tmp1X;
    this.norX*=tmp1X;
    this.norY*=tmp1X;
    this.norZ*=tmp1X;
    tmpM=this.body1.invertInertia.elements;
    this.invI1e00=tmpM[0];
    this.invI1e01=tmpM[1];
    this.invI1e02=tmpM[2];
    this.invI1e10=tmpM[3];
    this.invI1e11=tmpM[4];
    this.invI1e12=tmpM[5];
    this.invI1e20=tmpM[6];
    this.invI1e21=tmpM[7];
    this.invI1e22=tmpM[8];
    tmpM=this.body2.invertInertia.elements;
    this.invI2e00=tmpM[0];
    this.invI2e01=tmpM[1];
    this.invI2e02=tmpM[2];
    this.invI2e10=tmpM[3];
    this.invI2e11=tmpM[4];
    this.invI2e12=tmpM[5];
    this.invI2e20=tmpM[6];
    this.invI2e21=tmpM[7];
    this.invI2e22=tmpM[8];
    this.norTorque1X=this.relPos1Y*this.norZ-this.relPos1Z*this.norY;
    this.norTorque1Y=this.relPos1Z*this.norX-this.relPos1X*this.norZ;
    this.norTorque1Z=this.relPos1X*this.norY-this.relPos1Y*this.norX;
    this.norTorque2X=this.relPos2Y*this.norZ-this.relPos2Z*this.norY;
    this.norTorque2Y=this.relPos2Z*this.norX-this.relPos2X*this.norZ;
    this.norTorque2Z=this.relPos2X*this.norY-this.relPos2Y*this.norX;
    this.norTorqueUnit1X=this.norTorque1X*this.invI1e00+this.norTorque1Y*this.invI1e01+this.norTorque1Z*this.invI1e02;
    this.norTorqueUnit1Y=this.norTorque1X*this.invI1e10+this.norTorque1Y*this.invI1e11+this.norTorque1Z*this.invI1e12;
    this.norTorqueUnit1Z=this.norTorque1X*this.invI1e20+this.norTorque1Y*this.invI1e21+this.norTorque1Z*this.invI1e22;
    this.norTorqueUnit2X=this.norTorque2X*this.invI2e00+this.norTorque2Y*this.invI2e01+this.norTorque2Z*this.invI2e02;
    this.norTorqueUnit2Y=this.norTorque2X*this.invI2e10+this.norTorque2Y*this.invI2e11+this.norTorque2Z*this.invI2e12;
    this.norTorqueUnit2Z=this.norTorque2X*this.invI2e20+this.norTorque2Y*this.invI2e21+this.norTorque2Z*this.invI2e22;
    tmp1X=this.norTorque1X*this.invI1e00+this.norTorque1Y*this.invI1e01+this.norTorque1Z*this.invI1e02;
    tmp1Y=this.norTorque1X*this.invI1e10+this.norTorque1Y*this.invI1e11+this.norTorque1Z*this.invI1e12;
    tmp1Z=this.norTorque1X*this.invI1e20+this.norTorque1Y*this.invI1e21+this.norTorque1Z*this.invI1e22;
    tmp2X=tmp1Y*this.relPos1Z-tmp1Z*this.relPos1Y;
    tmp2Y=tmp1Z*this.relPos1X-tmp1X*this.relPos1Z;
    tmp2Z=tmp1X*this.relPos1Y-tmp1Y*this.relPos1X;
    tmp1X=this.norTorque2X*this.invI2e00+this.norTorque2Y*this.invI2e01+this.norTorque2Z*this.invI2e02;
    tmp1Y=this.norTorque2X*this.invI2e10+this.norTorque2Y*this.invI2e11+this.norTorque2Z*this.invI2e12;
    tmp1Z=this.norTorque2X*this.invI2e20+this.norTorque2Y*this.invI2e21+this.norTorque2Z*this.invI2e22;
    tmp2X+=tmp1Y*this.relPos2Z-tmp1Z*this.relPos2Y;
    tmp2Y+=tmp1Z*this.relPos2X-tmp1X*this.relPos2Z;
    tmp2Z+=tmp1X*this.relPos2Y-tmp1Y*this.relPos2X;
    this.normalDenominator=1/(this.invM1+this.invM2+this.norX*tmp2X+this.norY*tmp2Y+this.norZ*tmp2Z);
    tmp1X=this.norX*this.impulse;
    tmp1Y=this.norY*this.impulse;
    tmp1Z=this.norZ*this.impulse;
    this.lVel1.x+=tmp1X*this.invM1;
    this.lVel1.y+=tmp1Y*this.invM1;
    this.lVel1.z+=tmp1Z*this.invM1;
    this.aVel1.x+=this.norTorqueUnit1X*this.impulse;
    this.aVel1.y+=this.norTorqueUnit1Y*this.impulse;
    this.aVel1.z+=this.norTorqueUnit1Z*this.impulse;
    this.lVel2.x-=tmp1X*this.invM2;
    this.lVel2.y-=tmp1Y*this.invM2;
    this.lVel2.z-=tmp1Z*this.invM2;
    this.aVel2.x-=this.norTorqueUnit2X*this.impulse;
    this.aVel2.y-=this.norTorqueUnit2Y*this.impulse;
    this.aVel2.z-=this.norTorqueUnit2Z*this.impulse;
    if(this.posError<-0.005)this.posError+=0.005;
    else if(this.posError>0.005)this.posError-=0.005;
    else this.posError=0;
    this.targetNormalVelocity=this.posError*invTimeStep*0.05;
}
OIMO.DistanceJoint.prototype.solve = function () {
    var newImpulse;
    var rvn;
    var forceX;
    var forceY;
    var forceZ;
    var tmpX;
    var tmpY;
    var tmpZ;
    rvn=
    (this.lVel2.x-this.lVel1.x)*this.norX+(this.lVel2.y-this.lVel1.y)*this.norY+(this.lVel2.z-this.lVel1.z)*this.norZ+
    this.aVel2.x*this.norTorque2X+this.aVel2.y*this.norTorque2Y+this.aVel2.z*this.norTorque2Z-
    this.aVel1.x*this.norTorque1X-this.aVel1.y*this.norTorque1Y-this.aVel1.z*this.norTorque1Z
    ;
    newImpulse=(rvn-this.targetNormalVelocity)*this.normalDenominator;
    this.impulse+=newImpulse;
    forceX=this.norX*newImpulse;
    forceY=this.norY*newImpulse;
    forceZ=this.norZ*newImpulse;
    this.lVel1.x+=forceX*this.invM1;
    this.lVel1.y+=forceY*this.invM1;
    this.lVel1.z+=forceZ*this.invM1;
    this.aVel1.x+=this.norTorqueUnit1X*newImpulse;
    this.aVel1.y+=this.norTorqueUnit1Y*newImpulse;
    this.aVel1.z+=this.norTorqueUnit1Z*newImpulse;
    this.lVel2.x-=forceX*this.invM2;
    this.lVel2.y-=forceY*this.invM2;
    this.lVel2.z-=forceZ*this.invM2;
    this.aVel2.x-=this.norTorqueUnit2X*newImpulse;
    this.aVel2.y-=this.norTorqueUnit2Y*newImpulse;
    this.aVel2.z-=this.norTorqueUnit2Z*newImpulse;
}
OIMO.DistanceJoint.prototype.postSolve = function () {
}