OIMO.Contact = function(manifold){
    OIMO.Constraint.call( this);

    this.overlap=NaN;
    this.normalDenominator=NaN;
    this.tangentDenominator=NaN;
    this.binormalDenominator=NaN;
    this.shape1=null;
    this.shape2=null;
    this.warmStarted=false;
    this.lVel1=null;
    this.lVel2=null;
    this.aVel1=null;
    this.aVel2=null;
    this.relPos1X=NaN;
    this.relPos1Y=NaN;
    this.relPos1Z=NaN;
    this.relPos2X=NaN;
    this.relPos2Y=NaN;
    this.relPos2Z=NaN;
    this.relVelX=NaN;
    this.relVelY=NaN;
    this.relVelZ=NaN;
    this.norX=NaN;
    this.norY=NaN;
    this.norZ=NaN;
    this.tanX=NaN;
    this.tanY=NaN;
    this.tanZ=NaN;
    this.binX=NaN;
    this.binY=NaN;
    this.binZ=NaN;
    this.norTorque1X=NaN;
    this.norTorque1Y=NaN;
    this.norTorque1Z=NaN;
    this.norTorque2X=NaN;
    this.norTorque2Y=NaN;
    this.norTorque2Z=NaN;
    this.tanTorque1X=NaN;
    this.tanTorque1Y=NaN;
    this.tanTorque1Z=NaN;
    this.tanTorque2X=NaN;
    this.tanTorque2Y=NaN;
    this.tanTorque2Z=NaN;
    this.binTorque1X=NaN;
    this.binTorque1Y=NaN;
    this.binTorque1Z=NaN;
    this.binTorque2X=NaN;
    this.binTorque2Y=NaN;
    this.binTorque2Z=NaN;
    this.norTorqueUnit1X=NaN;
    this.norTorqueUnit1Y=NaN;
    this.norTorqueUnit1Z=NaN;
    this.norTorqueUnit2X=NaN;
    this.norTorqueUnit2Y=NaN;
    this.norTorqueUnit2Z=NaN;
    this.tanTorqueUnit1X=NaN;
    this.tanTorqueUnit1Y=NaN;
    this.tanTorqueUnit1Z=NaN;
    this.tanTorqueUnit2X=NaN;
    this.tanTorqueUnit2Y=NaN;
    this.tanTorqueUnit2Z=NaN;
    this.binTorqueUnit1X=NaN;
    this.binTorqueUnit1Y=NaN;
    this.binTorqueUnit1Z=NaN;
    this.binTorqueUnit2X=NaN;
    this.binTorqueUnit2Y=NaN;
    this.binTorqueUnit2Z=NaN;
    this.invM1=NaN;
    this.invM2=NaN;
    this.invI1e00=NaN;
    this.invI1e01=NaN;
    this.invI1e02=NaN;
    this.invI1e10=NaN;
    this.invI1e11=NaN;
    this.invI1e12=NaN;
    this.invI1e20=NaN;
    this.invI1e21=NaN;
    this.invI1e22=NaN;
    this.invI2e00=NaN;
    this.invI2e01=NaN;
    this.invI2e02=NaN;
    this.invI2e10=NaN;
    this.invI2e11=NaN;
    this.invI2e12=NaN;
    this.invI2e20=NaN;
    this.invI2e21=NaN;
    this.invI2e22=NaN;
    this.targetNormalVelocity=NaN;
    this.targetSeparateVelocity=NaN;
    this.friction=NaN;
    this.restitution=NaN;

    this.position=new OIMO.Vec3();
    this.relativePosition1=new OIMO.Vec3();
    this.relativePosition2=new OIMO.Vec3();
    this.normal=new OIMO.Vec3();
    this.tangent=new OIMO.Vec3();
    this.binormal=new OIMO.Vec3();
    this.shapeConnection1=new OIMO.ContactConnection(this);
    this.shapeConnection2=new OIMO.ContactConnection(this);
    this.bodyConnection1=new OIMO.ContactConnection(this);
    this.bodyConnection2=new OIMO.ContactConnection(this);
    this.id=new OIMO.ContactID();
    this.normalImpulse=0;
    this.tangentImpulse=0;
    this.binormalImpulse=0;
}
OIMO.Contact.prototype = Object.create( OIMO.Constraint.prototype );
OIMO.Contact.prototype.setupFromContactInfo = function(contactInfo){
    this.position.x=contactInfo.position.x;
    this.position.y=contactInfo.position.y;
    this.position.z=contactInfo.position.z;
    this.norX=contactInfo.normal.x;
    this.norY=contactInfo.normal.y;
    this.norZ=contactInfo.normal.z;
    this.overlap=contactInfo.overlap;
    this.shape1=contactInfo.shape1;
    this.shape2=contactInfo.shape2;
    this.body1=this.shape1.parent;
    this.body2=this.shape2.parent;
    this.bodyConnection1.connectedBody=this.body2;
    this.bodyConnection1.connectedShape=this.shape2;
    this.shapeConnection1.connectedBody=this.body2;
    this.shapeConnection1.connectedShape=this.shape2;
    this.bodyConnection2.connectedBody=this.body1;
    this.bodyConnection2.connectedShape=this.shape1;
    this.shapeConnection2.connectedBody=this.body1;
    this.shapeConnection2.connectedShape=this.shape1;
    this.relPos1X=this.position.x-this.body1.position.x;
    this.relPos1Y=this.position.y-this.body1.position.y;
    this.relPos1Z=this.position.z-this.body1.position.z;
    this.relPos2X=this.position.x-this.body2.position.x;
    this.relPos2Y=this.position.y-this.body2.position.y;
    this.relPos2Z=this.position.z-this.body2.position.z;
    this.lVel1=this.body1.linearVelocity;
    this.lVel2=this.body2.linearVelocity;
    this.aVel1=this.body1.angularVelocity;
    this.aVel2=this.body2.angularVelocity;
    this.invM1=this.body1.invertMass;
    this.invM2=this.body2.invertMass;
    var tmpI;
    tmpI=this.body1.invertInertia.elements;
    this.invI1e00=tmpI[0];
    this.invI1e01=tmpI[1];
    this.invI1e02=tmpI[2];
    this.invI1e10=tmpI[3];
    this.invI1e11=tmpI[4];
    this.invI1e12=tmpI[5];
    this.invI1e20=tmpI[6];
    this.invI1e21=tmpI[7];
    this.invI1e22=tmpI[8];
    tmpI=this.body2.invertInertia.elements;
    this.invI2e00=tmpI[0];
    this.invI2e01=tmpI[1];
    this.invI2e02=tmpI[2];
    this.invI2e10=tmpI[3];
    this.invI2e11=tmpI[4];
    this.invI2e12=tmpI[5];
    this.invI2e20=tmpI[6];
    this.invI2e21=tmpI[7];
    this.invI2e22=tmpI[8];
    this.id.data1=contactInfo.id.data1;
    this.id.data2=contactInfo.id.data2;
    this.id.flip=contactInfo.id.flip;
    this.friction=this.shape1.friction*this.shape2.friction;
    this.restitution=this.shape1.restitution*this.shape2.restitution;
    this.overlap=contactInfo.overlap;
    this.normalImpulse=0;
    this.tangentImpulse=0;
    this.binormalImpulse=0;
    this.warmStarted=false;
}
OIMO.Contact.prototype.removeReferences = function(){
    this.shape1=null;
    this.shape2=null;
    this.body1=null;
    this.body2=null;
    this.bodyConnection1.connectedBody=null;
    this.bodyConnection1.connectedShape=null;
    this.shapeConnection1.connectedBody=null;
    this.shapeConnection1.connectedShape=null;
    this.bodyConnection2.connectedBody=null;
    this.bodyConnection2.connectedShape=null;
    this.shapeConnection2.connectedBody=null;
    this.shapeConnection2.connectedShape=null;
}
OIMO.Contact.prototype.preSolve = function(timeStep,invTimeStep){
    this.relVelX=(this.lVel2.x+this.aVel2.y*this.relPos2Z-this.aVel2.z*this.relPos2Y)-(this.lVel1.x+this.aVel1.y*this.relPos1Z-this.aVel1.z*this.relPos1Y);
    this.relVelY=(this.lVel2.y+this.aVel2.z*this.relPos2X-this.aVel2.x*this.relPos2Z)-(this.lVel1.y+this.aVel1.z*this.relPos1X-this.aVel1.x*this.relPos1Z);
    this.relVelZ=(this.lVel2.z+this.aVel2.x*this.relPos2Y-this.aVel2.y*this.relPos2X)-(this.lVel1.z+this.aVel1.x*this.relPos1Y-this.aVel1.y*this.relPos1X);
    var rvn=this.norX*this.relVelX+this.norY*this.relVelY+this.norZ*this.relVelZ;
    this.tanX=this.relVelX-rvn*this.norX;
    this.tanY=this.relVelY-rvn*this.norY;
    this.tanZ=this.relVelZ-rvn*this.norZ;
    var len=this.tanX*this.tanX+this.tanY*this.tanY+this.tanZ*this.tanZ;
    if(len>1e-2){
    len=1/Math.sqrt(len);
    }else{
    this.tanX=this.norY*this.norX-this.norZ*this.norZ;
    this.tanY=-this.norZ*this.norY-this.norX*this.norX;
    this.tanZ=this.norX*this.norZ+this.norY*this.norY;
    len=1/Math.sqrt(this.tanX*this.tanX+this.tanY*this.tanY+this.tanZ*this.tanZ);
    }
    this.tanX*=len;
    this.tanY*=len;
    this.tanZ*=len;
    this.binX=this.norY*this.tanZ-this.norZ*this.tanY;
    this.binY=this.norZ*this.tanX-this.norX*this.tanZ;
    this.binZ=this.norX*this.tanY-this.norY*this.tanX;
    this.norTorque1X=this.relPos1Y*this.norZ-this.relPos1Z*this.norY;
    this.norTorque1Y=this.relPos1Z*this.norX-this.relPos1X*this.norZ;
    this.norTorque1Z=this.relPos1X*this.norY-this.relPos1Y*this.norX;
    this.norTorque2X=this.relPos2Y*this.norZ-this.relPos2Z*this.norY;
    this.norTorque2Y=this.relPos2Z*this.norX-this.relPos2X*this.norZ;
    this.norTorque2Z=this.relPos2X*this.norY-this.relPos2Y*this.norX;
    this.tanTorque1X=this.relPos1Y*this.tanZ-this.relPos1Z*this.tanY;
    this.tanTorque1Y=this.relPos1Z*this.tanX-this.relPos1X*this.tanZ;
    this.tanTorque1Z=this.relPos1X*this.tanY-this.relPos1Y*this.tanX;
    this.tanTorque2X=this.relPos2Y*this.tanZ-this.relPos2Z*this.tanY;
    this.tanTorque2Y=this.relPos2Z*this.tanX-this.relPos2X*this.tanZ;
    this.tanTorque2Z=this.relPos2X*this.tanY-this.relPos2Y*this.tanX;
    this.binTorque1X=this.relPos1Y*this.binZ-this.relPos1Z*this.binY;
    this.binTorque1Y=this.relPos1Z*this.binX-this.relPos1X*this.binZ;
    this.binTorque1Z=this.relPos1X*this.binY-this.relPos1Y*this.binX;
    this.binTorque2X=this.relPos2Y*this.binZ-this.relPos2Z*this.binY;
    this.binTorque2Y=this.relPos2Z*this.binX-this.relPos2X*this.binZ;
    this.binTorque2Z=this.relPos2X*this.binY-this.relPos2Y*this.binX;
    this.norTorqueUnit1X=this.norTorque1X*this.invI1e00+this.norTorque1Y*this.invI1e01+this.norTorque1Z*this.invI1e02;
    this.norTorqueUnit1Y=this.norTorque1X*this.invI1e10+this.norTorque1Y*this.invI1e11+this.norTorque1Z*this.invI1e12;
    this.norTorqueUnit1Z=this.norTorque1X*this.invI1e20+this.norTorque1Y*this.invI1e21+this.norTorque1Z*this.invI1e22;
    this.norTorqueUnit2X=this.norTorque2X*this.invI2e00+this.norTorque2Y*this.invI2e01+this.norTorque2Z*this.invI2e02;
    this.norTorqueUnit2Y=this.norTorque2X*this.invI2e10+this.norTorque2Y*this.invI2e11+this.norTorque2Z*this.invI2e12;
    this.norTorqueUnit2Z=this.norTorque2X*this.invI2e20+this.norTorque2Y*this.invI2e21+this.norTorque2Z*this.invI2e22;
    this.tanTorqueUnit1X=this.tanTorque1X*this.invI1e00+this.tanTorque1Y*this.invI1e01+this.tanTorque1Z*this.invI1e02;
    this.tanTorqueUnit1Y=this.tanTorque1X*this.invI1e10+this.tanTorque1Y*this.invI1e11+this.tanTorque1Z*this.invI1e12;
    this.tanTorqueUnit1Z=this.tanTorque1X*this.invI1e20+this.tanTorque1Y*this.invI1e21+this.tanTorque1Z*this.invI1e22;
    this.tanTorqueUnit2X=this.tanTorque2X*this.invI2e00+this.tanTorque2Y*this.invI2e01+this.tanTorque2Z*this.invI2e02;
    this.tanTorqueUnit2Y=this.tanTorque2X*this.invI2e10+this.tanTorque2Y*this.invI2e11+this.tanTorque2Z*this.invI2e12;
    this.tanTorqueUnit2Z=this.tanTorque2X*this.invI2e20+this.tanTorque2Y*this.invI2e21+this.tanTorque2Z*this.invI2e22;
    this.binTorqueUnit1X=this.binTorque1X*this.invI1e00+this.binTorque1Y*this.invI1e01+this.binTorque1Z*this.invI1e02;
    this.binTorqueUnit1Y=this.binTorque1X*this.invI1e10+this.binTorque1Y*this.invI1e11+this.binTorque1Z*this.invI1e12;
    this.binTorqueUnit1Z=this.binTorque1X*this.invI1e20+this.binTorque1Y*this.invI1e21+this.binTorque1Z*this.invI1e22;
    this.binTorqueUnit2X=this.binTorque2X*this.invI2e00+this.binTorque2Y*this.invI2e01+this.binTorque2Z*this.invI2e02;
    this.binTorqueUnit2Y=this.binTorque2X*this.invI2e10+this.binTorque2Y*this.invI2e11+this.binTorque2Z*this.invI2e12;
    this.binTorqueUnit2Z=this.binTorque2X*this.invI2e20+this.binTorque2Y*this.invI2e21+this.binTorque2Z*this.invI2e22;
    var tmp1X;
    var tmp1Y;
    var tmp1Z;
    var tmp2X;
    var tmp2Y;
    var tmp2Z;
    tmp1X=this.norTorque1X*this.invI1e00+this.norTorque1Y*this.invI1e01+this.norTorque1Z*this.invI1e02;
    tmp1Y=this.norTorque1X*this.invI1e10+this.norTorque1Y*this.invI1e11+this.norTorque1Z*this.invI1e12;
    tmp1Z=this.norTorque1X*this.invI1e20+this.norTorque1Y*this.invI1e21+this.norTorque1Z*this.invI1e22;
    tmp2X=tmp1Y*this.relPos1Z-tmp1Z*this.relPos1Y;
    tmp2Y=tmp1Z*this.relPos1X-tmp1X*this.relPos1Z;
    tmp2Z=tmp1X*this.relPos1Y-tmp1Y*this.relPos1X;
    tmp1X=this.norTorque2X*this.invI2e00+this.norTorque2Y*this.invI2e01+this.norTorque2Z*this.invI2e02;
    tmp1Y=this.norTorque2X*this.invI2e10+this.norTorque2Y*this.invI2e11+this.norTorque2Z*this.invI2e12;
    tmp1Z=this.norTorque2X*this.invI2e20+this.norTorque2Y*this.invI2e21+this.norTorque2Z*this.invI2e22;
    tmp2X+=tmp1Y*this.relPos2Z-tmp1Z*this.relPos2Y;
    tmp2Y+=tmp1Z*this.relPos2X-tmp1X*this.relPos2Z;
    tmp2Z+=tmp1X*this.relPos2Y-tmp1Y*this.relPos2X;
    this.normalDenominator=1/(this.invM1+this.invM2+this.norX*tmp2X+this.norY*tmp2Y+this.norZ*tmp2Z);
    tmp1X=this.tanTorque1X*this.invI1e00+this.tanTorque1Y*this.invI1e01+this.tanTorque1Z*this.invI1e02;
    tmp1Y=this.tanTorque1X*this.invI1e10+this.tanTorque1Y*this.invI1e11+this.tanTorque1Z*this.invI1e12;
    tmp1Z=this.tanTorque1X*this.invI1e20+this.tanTorque1Y*this.invI1e21+this.tanTorque1Z*this.invI1e22;
    tmp2X=tmp1Y*this.relPos1Z-tmp1Z*this.relPos1Y;
    tmp2Y=tmp1Z*this.relPos1X-tmp1X*this.relPos1Z;
    tmp2Z=tmp1X*this.relPos1Y-tmp1Y*this.relPos1X;
    tmp1X=this.tanTorque2X*this.invI2e00+this.tanTorque2Y*this.invI2e01+this.tanTorque2Z*this.invI2e02;
    tmp1Y=this.tanTorque2X*this.invI2e10+this.tanTorque2Y*this.invI2e11+this.tanTorque2Z*this.invI2e12;
    tmp1Z=this.tanTorque2X*this.invI2e20+this.tanTorque2Y*this.invI2e21+this.tanTorque2Z*this.invI2e22;
    tmp2X+=tmp1Y*this.relPos2Z-tmp1Z*this.relPos2Y;
    tmp2Y+=tmp1Z*this.relPos2X-tmp1X*this.relPos2Z;
    tmp2Z+=tmp1X*this.relPos2Y-tmp1Y*this.relPos2X;
    this.tangentDenominator=1/(this.invM1+this.invM2+this.tanX*tmp2X+this.tanY*tmp2Y+this.tanZ*tmp2Z);
    tmp1X=this.binTorque1X*this.invI1e00+this.binTorque1Y*this.invI1e01+this.binTorque1Z*this.invI1e02;
    tmp1Y=this.binTorque1X*this.invI1e10+this.binTorque1Y*this.invI1e11+this.binTorque1Z*this.invI1e12;
    tmp1Z=this.binTorque1X*this.invI1e20+this.binTorque1Y*this.invI1e21+this.binTorque1Z*this.invI1e22;
    tmp2X=tmp1Y*this.relPos1Z-tmp1Z*this.relPos1Y;
    tmp2Y=tmp1Z*this.relPos1X-tmp1X*this.relPos1Z;
    tmp2Z=tmp1X*this.relPos1Y-tmp1Y*this.relPos1X;
    tmp1X=this.binTorque2X*this.invI2e00+this.binTorque2Y*this.invI2e01+this.binTorque2Z*this.invI2e02;
    tmp1Y=this.binTorque2X*this.invI2e10+this.binTorque2Y*this.invI2e11+this.binTorque2Z*this.invI2e12;
    tmp1Z=this.binTorque2X*this.invI2e20+this.binTorque2Y*this.invI2e21+this.binTorque2Z*this.invI2e22;
    tmp2X+=tmp1Y*this.relPos2Z-tmp1Z*this.relPos2Y;
    tmp2Y+=tmp1Z*this.relPos2X-tmp1X*this.relPos2Z;
    tmp2Z+=tmp1X*this.relPos2Y-tmp1Y*this.relPos2X;
    this.binormalDenominator=1/(this.invM1+this.invM2+this.binX*tmp2X+this.binY*tmp2Y+this.binZ*tmp2Z);
    if(this.warmStarted){
    this.tangentImpulse*=0.95;
    this.binormalImpulse*=0.95;
    tmp1X=this.norX*this.normalImpulse+this.tanX*this.tangentImpulse+this.binX*this.binormalImpulse;
    tmp1Y=this.norY*this.normalImpulse+this.tanY*this.tangentImpulse+this.binY*this.binormalImpulse;
    tmp1Z=this.norZ*this.normalImpulse+this.tanZ*this.tangentImpulse+this.binZ*this.binormalImpulse;
    this.lVel1.x+=tmp1X*this.invM1;
    this.lVel1.y+=tmp1Y*this.invM1;
    this.lVel1.z+=tmp1Z*this.invM1;
    this.aVel1.x+=this.norTorqueUnit1X*this.normalImpulse+this.tanTorqueUnit1X*this.tangentImpulse+this.binTorqueUnit1X*this.binormalImpulse;
    this.aVel1.y+=this.norTorqueUnit1Y*this.normalImpulse+this.tanTorqueUnit1Y*this.tangentImpulse+this.binTorqueUnit1Y*this.binormalImpulse;
    this.aVel1.z+=this.norTorqueUnit1Z*this.normalImpulse+this.tanTorqueUnit1Z*this.tangentImpulse+this.binTorqueUnit1Z*this.binormalImpulse;
    this.lVel2.x-=tmp1X*this.invM2;
    this.lVel2.y-=tmp1Y*this.invM2;
    this.lVel2.z-=tmp1Z*this.invM2;
    this.aVel2.x-=this.norTorqueUnit2X*this.normalImpulse+this.tanTorqueUnit2X*this.tangentImpulse+this.binTorqueUnit2X*this.binormalImpulse;
    this.aVel2.y-=this.norTorqueUnit2Y*this.normalImpulse+this.tanTorqueUnit2Y*this.tangentImpulse+this.binTorqueUnit2Y*this.binormalImpulse;
    this.aVel2.z-=this.norTorqueUnit2Z*this.normalImpulse+this.tanTorqueUnit2Z*this.tangentImpulse+this.binTorqueUnit2Z*this.binormalImpulse;
    rvn=0;
    }
    if(rvn>-1){
    rvn=0;
    }
    this.targetNormalVelocity=this.restitution*-rvn;
    var separationalVelocity=-this.overlap-0.005;
    if(separationalVelocity>0){
    separationalVelocity*=invTimeStep*0.05;
    if(this.targetNormalVelocity<separationalVelocity){
    this.targetNormalVelocity=separationalVelocity;
    }
    }
}
OIMO.Contact.prototype.solve = function(){
    var error;
    var oldImpulse1;
    var newImpulse1;
    var oldImpulse2;
    var newImpulse2;
    var rvn;
    var forceX;
    var forceY;
    var forceZ;
    var tmpX;
    var tmpY;
    var tmpZ;
    rvn=
    (this.lVel2.x-this.lVel1.x)*this.norX+(this.lVel2.y-this.lVel1.y)*this.norY+(this.lVel2.z-this.lVel1.z)*this.norZ+
    this.aVel2.x*this.norTorque2X+this.aVel2.y*this.norTorque2Y+this.aVel2.z*this.norTorque2Z-
    this.aVel1.x*this.norTorque1X-this.aVel1.y*this.norTorque1Y-this.aVel1.z*this.norTorque1Z
    ;
    oldImpulse1=this.normalImpulse;
    newImpulse1=(rvn-this.targetNormalVelocity)*this.normalDenominator*1.4;
    this.normalImpulse+=newImpulse1;
    if(this.normalImpulse>0)this.normalImpulse=0;
    newImpulse1=this.normalImpulse-oldImpulse1;
    forceX=this.norX*newImpulse1;
    forceY=this.norY*newImpulse1;
    forceZ=this.norZ*newImpulse1;
    this.lVel1.x+=forceX*this.invM1;
    this.lVel1.y+=forceY*this.invM1;
    this.lVel1.z+=forceZ*this.invM1;
    this.aVel1.x+=this.norTorqueUnit1X*newImpulse1;
    this.aVel1.y+=this.norTorqueUnit1Y*newImpulse1;
    this.aVel1.z+=this.norTorqueUnit1Z*newImpulse1;
    this.lVel2.x-=forceX*this.invM2;
    this.lVel2.y-=forceY*this.invM2;
    this.lVel2.z-=forceZ*this.invM2;
    this.aVel2.x-=this.norTorqueUnit2X*newImpulse1;
    this.aVel2.y-=this.norTorqueUnit2Y*newImpulse1;
    this.aVel2.z-=this.norTorqueUnit2Z*newImpulse1;
    var max=-this.normalImpulse*this.friction;
    this.relVelX=this.lVel2.x-this.lVel1.x;
    this.relVelY=this.lVel2.y-this.lVel1.y;
    this.relVelZ=this.lVel2.z-this.lVel1.z;
    rvn=
    this.relVelX*this.tanX+this.relVelY*this.tanY+this.relVelZ*this.tanZ+
    this.aVel2.x*this.tanTorque2X+this.aVel2.y*this.tanTorque2Y+this.aVel2.z*this.tanTorque2Z-
    this.aVel1.x*this.tanTorque1X-this.aVel1.y*this.tanTorque1Y-this.aVel1.z*this.tanTorque1Z
    ;
    oldImpulse1=this.tangentImpulse;
    newImpulse1=rvn*this.tangentDenominator;
    this.tangentImpulse+=newImpulse1;
    rvn=
    this.relVelX*this.binX+this.relVelY*this.binY+this.relVelZ*this.binZ+
    this.aVel2.x*this.binTorque2X+this.aVel2.y*this.binTorque2Y+this.aVel2.z*this.binTorque2Z-
    this.aVel1.x*this.binTorque1X-this.aVel1.y*this.binTorque1Y-this.aVel1.z*this.binTorque1Z
    ;
    oldImpulse2=this.binormalImpulse;
    newImpulse2=rvn*this.binormalDenominator;
    this.binormalImpulse+=newImpulse2;
    var len=this.tangentImpulse*this.tangentImpulse+this.binormalImpulse*this.binormalImpulse;
    if(len>max*max){
    len=max/Math.sqrt(len);
    this.tangentImpulse*=len;
    this.binormalImpulse*=len;
    }
    newImpulse1=this.tangentImpulse-oldImpulse1;
    newImpulse2=this.binormalImpulse-oldImpulse2;
    forceX=this.tanX*newImpulse1+this.binX*newImpulse2;
    forceY=this.tanY*newImpulse1+this.binY*newImpulse2;
    forceZ=this.tanZ*newImpulse1+this.binZ*newImpulse2;
    this.lVel1.x+=forceX*this.invM1;
    this.lVel1.y+=forceY*this.invM1;
    this.lVel1.z+=forceZ*this.invM1;
    this.aVel1.x+=this.tanTorqueUnit1X*newImpulse1+this.binTorqueUnit1X*newImpulse2;
    this.aVel1.y+=this.tanTorqueUnit1Y*newImpulse1+this.binTorqueUnit1Y*newImpulse2;
    this.aVel1.z+=this.tanTorqueUnit1Z*newImpulse1+this.binTorqueUnit1Z*newImpulse2;
    this.lVel2.x-=forceX*this.invM2;
    this.lVel2.y-=forceY*this.invM2;
    this.lVel2.z-=forceZ*this.invM2;
    this.aVel2.x-=this.tanTorqueUnit2X*newImpulse1+this.binTorqueUnit2X*newImpulse2;
    this.aVel2.y-=this.tanTorqueUnit2Y*newImpulse1+this.binTorqueUnit2Y*newImpulse2;
    this.aVel2.z-=this.tanTorqueUnit2Z*newImpulse1+this.binTorqueUnit2Z*newImpulse2;
}
OIMO.Contact.prototype.postSolve = function(){
    this.relativePosition1.x=this.relPos1X;
    this.relativePosition1.y=this.relPos1Y;
    this.relativePosition1.z=this.relPos1Z;
    this.relativePosition2.x=this.relPos2X;
    this.relativePosition2.y=this.relPos2Y;
    this.relativePosition2.z=this.relPos2Z;
    this.normal.x=this.norX;
    this.normal.y=this.norY;
    this.normal.z=this.norZ;
    this.tangent.x=this.tanX;
    this.tangent.y=this.tanY;
    this.tangent.z=this.tanZ;
    this.binormal.x=this.binX;
    this.binormal.y=this.binY;
    this.binormal.z=this.binZ;
}